import { Injectable, inject } from '@angular/core';
import { IMenuItem } from '../interfaces/menu.model';
import { AuthService } from './auth.service';

@Injectable({
  providedIn: 'root',
})
export class SidebarService {
  private authS = inject(AuthService);

  get onLoadMenu() {
    return this.menu;
  }
  menu: IMenuItem[] = [
    // {
    //   visible: this.authS.onValidateRoles(['SuperUsuario']),
    //   label: 'CONFIGURACION',
    //   isTitle: true,
    // },
    {
      visible: this.authS.onValidateRoles(['SuperUsuario']),
      label: 'Catalogos',
      icon: 'fa-duotone fa-solid fa-album-collection',
      name: 'catalog',
      items: [
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Modulos App',
          routerLink: '/catalog/module-app',
          name: 'module-app',
        },
        // {
        //   visible: this.authS.onValidateRoles(['SuperUsuario']),
        //   label: 'Administradoras',
        //   routerLink: '/catalog/administrators',
        //   name: 'module-app',
        // },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Bancos',
          routerLink: '/catalog/banks',
          name: 'bancos',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Forma de pago',
          routerLink: '/catalog/forma-pago',
          name: 'forma de pago',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Metodo de pago',
          routerLink: '/catalog/metodo-pago',
          name: 'metodo de pago',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Uso de cfdi',
          routerLink: '/catalog/uso-cfdi',
          name: 'uso de cfdi',
        },

        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Departamentos de trabajo',
          routerLink: '/catalog/company-departaments',
          name: 'company-departaments',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Puestos de trabajo',
          routerLink: '/catalog/jobs',
          name: 'jobs',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Categorias ticket',
          routerLink: '/catalog/ticket-group-category',
          name: 'ticket group category',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Categoria Medidor',
          routerLink: '/catalog/meter-category',
          name: 'meter category',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Categoria productos',
          routerLink: '/catalog/product-category',
          name: 'product category',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Productos y servicios',
          routerLink: '/catalog/products-services',
          name: 'products-services',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Clasificacion equipos',
          routerLink: '/catalog/machinery-classification',
          name: 'machinery-classification',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Unidades de medida',
          routerLink: '/catalog/units-of-measurement',
          name: 'units-of-measurement',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Entrega Recepción',
          routerLink: '/catalog/entrega-recepcion-cliente',
          name: 'entrega recepcion',
        },

        // {
        //   visible: this.authS.onValidateRoles([
        //     'GerenteMantenimiento',
        //     'JefeMantenimiento',
        //     'Administrador',
        //     'SuperUsuario',
        //   ]),
        //   label: 'Nomenclatura',
        //   routerLink: '/documento/nomenclatura',
        //   name: 'Capacitación-Nomenclatura',
        // },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Calendario Maestro Equipo',
          routerLink: '/calendario/calendario-maestro-equipo',
          name: 'Capacitación-Guia calendario general de mtto',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles(['SuperUsuario']),
      label: 'Mails empresa',
      icon: 'fa-duotone fa-solid fa-envelope',
      name: 'Mails empresa',
      items: [
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Emails corporativos',
          routerLink: '/settings/customer-data-company',
          name: 'customer-data-company',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Datos de email',
          routerLink: '/settings/datos-email',
          name: 'datos de correos',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Depuración',
          routerLink: '/settings/depuration',
          name: 'depuration',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles(['Sistemas', 'SuperUsuario']),
      label: 'Usuarios',
      icon: 'fa-duotone fa-solid fa-user-tie',
      routerLink: '/accounts',
    },
    {
      visible: this.authS.canRead('LEGAL'),
      label: 'Legal',
      icon: 'fa-duotone fa-solid fa-gavel',
      items: [
        {
          visible: this.authS.canRead('LEGAL'),
          label: 'Minutas',
          routerLink: '/contabilidad/pendientes-minutas-legal',
          name: 'Legal-Minutas',
        },
        {
          visible: this.authS.canRead('LEGAL'),
          label: 'Legal Tickets',
          routerLink: '/legal/list-ticket-legal',
          name: 'Tickets',
        },
        {
          visible: this.authS.canRead('LEGAL'),
          label: 'Pendientes',
          routerLink: '/legal/pendings',
          name: 'pendientes legal',
        },
        {
          visible: this.authS.canRead('LEGAL'),
          label: 'Reportes Internos',
          routerLink: '/legal/reports-internal',
          name: 'reportes legal',
        },
        {
          visible: this.authS.canRead('LEGAL'),
          label: 'Reportes Externos',
          routerLink: '/legal/reports-external',
          name: 'reportes legal',
        },
        {
          visible: this.authS.canRead('LEGAL'),
          label: 'Categorias y asuntos',
          routerLink: '/legal/legal-matter',
          name: 'reportes legal',
        },
        {
          visible: this.authS.canRead('LEGAL'),
          label: 'Comites',
          routerLink: '/directory/comites',
          name: 'comites',
        },
        {
          visible: this.authS.canRead('LEGAL'),
          label: 'Polizas',
          routerLink: '/documento/contracts-policies-view-legal',
          name: 'polizas',
        },
      ],
    },
    {
      visible: this.authS.canRead('CONTABILIDAD'),
      label: 'Contabilidad',
      icon: 'fa-duotone fa-solid fa-hand-holding-dollar',
      items: [
        {
          visible: this.authS.canRead('CONTABILIDAD'),
          label: 'Presentaciones',
          routerLink: '/operaciones/presentacion-junta-comite/presentaciones',
          name: 'Contabilidad-Presentaciones',
        },
        {
          visible: this.authS.canRead('CONTABILIDAD'),
          label: 'Minutas',
          routerLink: '/contabilidad/pendientes-minutas',
          name: 'Contabilidad-Pendientes-Minutas',
        },
        {
          visible: this.authS.canRead('CONTABILIDAD'),
          label: 'Estados Financieros',
          routerLink: '/contabilidad/estados-financieros',
          name: 'Estados financieros',
        },
        {
          visible: this.authS.canRead('CONTABILIDAD'),
          label: 'Presupuesto',
          routerLink: '/operaciones/compras/cedula-cliente',
          name: 'Contabilidad-Presupuesto',
        },
        {
          visible: this.authS.canRead('CONTABILIDAD'),
          label: 'Reporte Envio Financieros',
          routerLink: '/contabilidad/reporte-envio-financieros',
          name: 'Reporte-Envio-Financieros',
        },
        {
          visible: this.authS.canRead('CONTABILIDAD'),
          label: 'Catalogo de cuentas',
          routerLink: '/contabilidad/catalogo-cuentas',
          name: 'Cuentas',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles(['Sistemas', 'SuperUsuario']),
      label: '4.-Sistemas',
      icon: 'fa-duotone fa-solid fa-laptop-code',
      items: [
        {
          visible: this.authS.onValidateRoles(['Sistemas', 'SuperUsuario']),
          label: 'Tickets',
          routerLink: '/sistemas/ticket-sistemas',
          name: 'Sistemas-Tickets',
        },
      ],
    },
    // {
    //   visible: this.authS.onValidateRoles(['SuperUsuario']),
    //   label: 'OPERACIONES',
    //   isTitle: true,
    // },

    {
      visible: this.authS.canRead('SUPERVISION'),
      label: '5.1 Supervisión',
      icon: 'fa-duotone fa-solid fa-user-tie',
      items: [
        {
          visible: this.authS.canRead('SUPERVISION'),
          label: 'Bitácora Diaria',
          routerLink: '/supervision/agenda-supervision',
          name: 'Supervisión-Bitacora Diaria',
        },
        {
          visible: this.authS.canRead('SUPERVISION'),
          label: 'Resultado General',
          routerLink: '//supervision/resultado-general-dashboard',
          name: 'Supervisión-Resultado General',
        },
        {
          visible: this.authS.canRead('SUPERVISION'),
          label: 'Reporte Presentaciones',
          routerLink: '//supervision/presentaciones-juntas-comite',
          name: 'Supervisión-Reporte presentaciónes juntas de comité',
        },
        {
          visible: this.authS.canRead('SUPERVISION'),
          label: 'Reporte Minutas',
          routerLink: '/supervision/minutas-resumen',
          name: 'Supervisión-Reporte minutas',
        },
        {
          visible: this.authS.canRead('SUPERVISION'),
          label: 'Reporte Ticket',
          routerLink: '/supervision/reporte-tickets',
          name: 'Supervisión-Reporte tickets',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles([
        'GerenteMantenimiento',
        'SuperUsuario',
      ]),
      label: '5.2 Entrega Recepción',
      icon: 'fa-duotone fa-solid fa-truck',
      items: [
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'SuperUsuario',
          ]),
          label: 'General',
          routerLink: '/entrega-recepcion/general',
          name: 'Supervisión-Entrega recepción',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'SuperUsuario',
          ]),
          label: 'Equipos',
          routerLink: '/entrega-recepcion/equipos',
          name: 'Supervisión-Entrega recepción-Equipos',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'SuperUsuario',
          ]),
          label: 'Instalaciones',
          routerLink: '/entrega-recepcion/instalaciones',
          name: 'Supervisión-Entrega recepción-Instalaciones',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'SuperUsuario',
          ]),
          label: 'Extintores',
          routerLink: '/entrega-recepcion/hidrantes',
          name: 'Supervisión-Entrega recepción-Hidrantes',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'SuperUsuario',
          ]),
          label: 'Llaves',
          routerLink: '/entrega-recepcion/llaves',
          name: 'Supervisión-Entrega recepción-Llaves',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'SuperUsuario',
          ]),
          label: 'Herramientas',
          routerLink: '/entrega-recepcion/herramientas',
          name: 'Supervisión-Entrega recepción-Herramientas',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'SuperUsuario',
          ]),
          label: 'Mantenimientos',
          routerLink: '/entrega-recepcion/mantenimientos',
          name: 'Supervisión-Entrega recepción-Mantenimientos',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'SuperUsuario',
          ]),
          label: 'Pendientes',
          routerLink: 'operaciones/entrega-recepcion/mantenimientos-pendientes',
          name: 'Supervisión-Entrega recepción-Pendientes',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'SuperUsuario',
          ]),
          label: 'Organigrama',
          routerLink: '/entrega-recepcion/organigrama',
          name: 'Supervisión-Entrega recepción-Organigrama',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'SuperUsuario',
          ]),
          label: 'Planos',
          routerLink: '/entrega-recepcion/planos',
          name: 'Supervisión-Entrega recepción-Planos',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'SuperUsuario',
          ]),
          label: 'Insumos',
          routerLink: '/entrega-recepcion/insumos',
          name: 'Supervisión-Entrega recepción-Insumos',
        },
      ],
    },
    {
      visible: this.authS.canRead('MIEDIFICIO'),
      label: '5.3 Mi Edificio',
      icon: 'fa-duotone fa-solid fa-house-building',
      routerLink: '/operaciones/mi-edificio',
      name: 'Mi edificio',
    },
    {
      visible: this.authS.canRead('MIEDIFICIO'),
      label: '5.4 Dashboard',
      icon: 'fa-duotone fa-solid fa-grid-horizontal',
      routerLink: '/dashboard/panel',
      name: 'Dashboard',
    },
    {
      visible: this.authS.canRead('TICKET'),
      label: '5.5 Tickets',
      icon: 'fa-duotone fa-solid fa-ticket',
      name: 'Tickets',
      items: [
        {
          visible: this.authS.canRead('TICKET'),
          label: 'Grupos',
          routerLink: '/tickets/list',
          name: 'groups',
        },
        {
          visible: this.authS.canRead('TICKET'),
          label: 'Asignados a mi',
          routerLink: '/tickets/my-tickets',
          name: 'my assignments',
        },
        {
          visible: this.authS.canRead('TICKET'),
          label: 'Mis solicitudes',
          routerLink: '/tickets/my-requests',
          name: 'my request',
        },
        // {
        //   visible: this.authS.canRead('TICKET'),
        //   label: 'Plan de trabajo',
        //   routerLink: '/tickets/work-plan',
        //   name: 'pending',
        // },
        // {
        //   visible: this.authS.canRead('TICKET'),
        //   label: 'Reporte semanal',
        //   routerLink: '/tickets/weekly-report',
        //   name: 'weekly-report',
        // },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Reportes',
          routerLink: '/tickets/reports',
          name: 'message report',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles([
        'Asistente',
        'Colaborador',
        'Direccion',
        'GerenteMantenimiento',
        'JefeMantenimiento',
        'Administrador',
        'SuperUsuario',
        'SupervisionOperativa',
      ]),
      label: '5.6 Juntas con comite',
      icon: 'fa-duotone fa-solid fa-person-chalkboard',
      name: 'Juntas con comite',
      items: [
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Presentacion JC',
          routerLink: '/operaciones/presentacion-junta-comite/presentaciones',
          name: 'Operaciones-Presentaciones juntas de comité',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Minutas',
          routerLink: '/operaciones/junta-comite/minutas',
          name: 'Operaciones-Minuta',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles([
        'SuperUsuario',
        'JefeMantenimiento',
        'Asistente',
        'JefeMantenimiento',
        'Administrador',
      ]),
      label: '5.2-Compras',
      icon: 'fa-duotone fa-solid fa-bag-shopping',
      items: [
        {
          visible: this.authS.onValidateRoles([
            'SuperUsuario',
            'Asistente',
            'JefeMantenimiento',
            'Administrador',
            'Contador',
          ]),

          label: 'Ultimo Presupuesto',
          routerLink: '/operaciones/compras/cedula-cliente',
          name: 'Compras-Cedula presupuestal',
        },
        {
          visible: this.authS.onValidateRoles([
            'SuperUsuario',
            'Asistente',
            'JefeMantenimiento',
            'Administrador',
            'Contador',
          ]),

          label: 'Presupuestos',
          routerLink: '/operaciones/compras/presupuestos',
          name: 'Compras-Cedula presupuestal',
        },
        {
          visible: this.authS.onValidateRoles([
            'SuperUsuario',
            'Asistente',
            'Administrador',
          ]),

          label: 'Cuentas Mtto',
          routerLink: '/operaciones/compras/mtto-presupuesto',
          name: 'Compras-Cuentas Mtto',
        },
        {
          visible: this.authS.onValidateRoles([
            'SuperUsuario',
            'Asistente',
            'JefeMantenimiento',
            'Administrador',
          ]),

          label: 'Productos y servicios',
          routerLink: '/catalog/products-services',
          name: 'Compras-Productos y servicios',
        },
        {
          visible: this.authS.onValidateRoles([
            'SuperUsuario',
            'Asistente',
            'JefeMantenimiento',
            'Administrador',
          ]),
          label: 'Solicitud compra',
          routerLink: '/operaciones/compras/solicitudes-compra',
          name: 'Compras-Solicitudes de compra',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'Administrador',
            'SuperUsuario',
            'JefeMantenimiento',
          ]),
          label: 'OC Fijos',
          routerLink: '/operaciones/compras/ordenes-compra-fijos',
          name: 'Compras-ordenes de compra gastos fijos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'Administrador',
            'SuperUsuario',
            'JefeMantenimiento',
          ]),
          label: 'OC Variables',
          routerLink: '/operaciones/compras/ordenes-compra',
          name: 'Compras-ordenes de compra gastos variables',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Catalogo OC Fijos',
          routerLink: '/operaciones/compras/catalogo-gastos-fijos',
          name: 'Compras-catalogo ordenes de compra gastos fijos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'OC Pagadas',
          routerLink: '/operaciones/compras/pagadas',
          name: 'Compras-ordenes de compra pagadas',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles([
        'Asistente',
        'Colaborador',
        'Direccion',
        'GerenteMantenimiento',
        'JefeMantenimiento',
        'Administrador',
        'SuperUsuario',
        'SupervisionOperativa',
      ]),
      label: '5.7 Mtto preventivo',
      icon: 'fa-duotone fa-solid fa-screwdriver-wrench',
      name: 'Mantenimiento preventivo',
      items: [
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Ordenes de servicio',
          routerLink: '/operaciones/mantenimiento-preventivo',
          name: 'Operaciones-Mantenimientos preventivos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),

          label: 'Reporte mensual',
          routerLink: '/report/maintenance-report/panel',
          name: 'Reporte mensual',
        },
      ],
    },
    // {
    //   visible: this.authS.onValidateRoles(['SuperUsuario']),
    //   label: '5.-Tickets',
    //   icon: 'fa-duotone fa-solid fa-ticket',
    //   routerLink: '/tickets/panel',
    //   name: 'Tickets',
    // },
    // {
    //   visible: this.authS.onValidateRoles([
    //     'Asistente',
    //     'Colaborador',
    //     'Direccion',
    //     'GerenteMantenimiento',
    //     'JefeMantenimiento',
    //     'Administrador',
    //     'SuperUsuario',
    //     'SupervisionOperativa',
    //   ]),
    //   label: '5.1-Operaciones',
    //   icon: 'fa-duotone fa-solid fa-person-chalkboard',
    //   items: [
    //     // {
    //     //   visible: this.authS.onValidateRoles([
    //     //     'Asistente',
    //     //     'Colaborador',
    //     //     'GerenteMantenimiento',
    //     //     'JefeMantenimiento',
    //     //     'Administrador',
    //     //     'SuperUsuario',
    //     //     'SupervisionOperativa',
    //     //   ]),
    //     //   label: 'Tickets',
    //     //   routerLink: '/operaciones/reporte/tiket-mantenimiento',
    //     //   name: 'Operaciones-Tickets',
    //     // },
    //   ],
    // },
    {
      visible: this.authS.onValidateRoles([
        'Asistente',
        'Colaborador',
        'Direccion',
        'GerenteMantenimiento',
        'JefeMantenimiento',
        'Administrador',
        'SuperUsuario',
        'SupervisionOperativa',
      ]),
      label: '5.8 Mtto Bitacoras',
      icon: 'fa-duotone fa-solid fa-book',
      name: 'Mtto Bitacoras',
      items: [
        {
          visible: this.authS.onValidateRoles([
            'SuperUsuario',
            'Colaborador',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
          ]),
          label: 'Recorrido diario',
          routerLink: '/logbook/recorrido',
          name: 'Bitacoras-mantenimiento recorrido diario',
        },
        {
          visible: this.authS.onValidateRoles([
            'Colaborador',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Consumos lecturas',
          routerLink: '/logbook/lista-medidor',
          name: 'Bitacoras-medidores gas, agua y luz',
        },
        {
          visible: this.authS.onValidateRoles([
            'Colaborador',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Albercas',
          routerLink: '/logbook/piscina',
          name: 'Bitacoras-alberca',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'Asistente',
            'SuperUsuario',
          ]),
          label: 'Llamados Emergencia Elevadores',
          routerLink: '/logbook/elevators-emergency-call',
          name: 'Reporte de elevadores',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'Asistente',
            'SuperUsuario',
          ]),
          label: 'Refacciones Elevadores',
          routerLink: '/logbook/elevator-spare-parts-change',
          name: 'Cambio de refacciones elevadores',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles([
        'Asistente',
        'GerenteMantenimiento',
        'JefeMantenimiento',
        'Administrador',
        'SuperUsuario',
      ]),
      label: '5.9 Almacén',
      icon: 'fa-duotone fa-solid fa-boxes-stacked',
      items: [
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Inventario productos',
          routerLink: '/almacen/inventario-productos',
          name: 'Inventarios-Entradas de insumos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Entradas de insumos',
          routerLink: '/almacen/entrada-productos',
          name: 'Inventarios-Entradas de insumos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Salidas de insumos',
          routerLink: '/almacen/salida-productos',
          name: 'Inventarios-Salida de insumos',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Préstamo de herramientas',
          routerLink: '/almacen/prestamo-herramienta',
          name: 'Inventarios-Préstamo de herramientas',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles([
        'Asistente',
        'Colaborador',
        'GerenteMantenimiento',
        'JefeMantenimiento',
        'Administrador',
        'Sistemas',
        'SuperUsuario',
      ]),
      label: '5.10 Inventarios',
      icon: 'fa-duotone fa-solid fa-store',
      items: [
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Amenidades',
          routerLink: '/mantenimiento/inventario/equipos/2',
          name: 'Inventarios-Equipos',
        },

        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Áreas Comunes',
          routerLink: '/mantenimiento/inventario/equipos/8',
          name: 'Inventarios-Areas comunes',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Cuartos de Maquinas',
          routerLink: '/mantenimiento/inventario/equipos/7',
          name: 'Inventarios-Cuartos de maquinas',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Mobiliario',
          routerLink: '/mantenimiento/inventario/equipos/3',
          name: 'Inventarios-Mobiliarios',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Llaves',
          routerLink: '/mantenimiento/inventario/llaves',
          name: 'Inventarios-Llaves',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Herramientas',
          routerLink: '/mantenimiento/inventario/herramienta',
          name: 'Inventarios-Herramienta',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Radios',
          routerLink: '/mantenimiento/inventario/radios',
          name: 'Inventarios-Radios',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'Sistemas',
            'SuperUsuario',
          ]),
          label: 'EQ. Sistemas-CCTV',
          routerLink: '/mantenimiento/inventario/equipos/6',
          name: 'Inventarios-Equipos de sistemas',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Equipos electromecánicos',
          routerLink: '/mantenimiento/inventario/equipos/1',
          name: 'Inventarios-Equipos electromecanicos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Equipos de Gimnasio',
          routerLink: '/mantenimiento/inventario/equipos/5',
          name: 'Inventarios-Equipos de gimnasio',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Extintores',
          routerLink: '/catalog/extintores',
          name: 'Inventarios-Extintores',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Extintores 2',
          routerLink: '/catalog/extintores-group',
          name: 'Inventarios-Extintores',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles([
        'GerenteMantenimiento',
        'JefeMantenimiento',
        'Administrador',
        'SuperUsuario',
      ]),
      label: '5.11 Bliblioteca',
      icon: 'ffa-duotone fa-solid fa-books',
      name: 'Bliblioteca',
      items: [
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Polizas de Mtto',
          routerLink: '/documento/poliza',
          name: 'Inventarios-Polizas de mantenimiento',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Documentos',
          routerLink: '/documento/documento',
          name: 'Inventarios-Documentos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Manuales y procesos',
          routerLink: '/documento/procesos',
          name: 'Capacitación-Manuales y procesos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Formatos',
          routerLink: '/documento/formatos',
          name: 'Capacitación-Formatos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Comunicados internos',
          routerLink: '/documento/comunicado',
          name: 'Capacitación-Comunicados internos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Mttos Preventivos',
          routerLink: '/calendario/mantenimiento-master',
          name: 'Calendario-Mantenimientos preventivos',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'EQ. Iluminación',
          routerLink: '/catalog/iluminacion',
          name: 'Inventarios-Catalogo de iluminación',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Pintura Especificación',
          routerLink: '/catalog/pintura',
          name: 'Inventarios-Catalogo de pintura',
        },
      ],
    },

    {
      visible: this.authS.onValidateRoles([
        'Asistente',
        'GerenteMantenimiento',
        'JefeMantenimiento',
        'Administrador',
        'SuperUsuario',
        'SupervisionOperativa',
      ]),
      label: '5.12 Calendarios',
      icon: 'fa-duotone fa-solid fa-calendar',
      items: [
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'Contador',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Fondeos',
          routerLink: '/calendario/fondeos',
          name: 'Calendario-Fondeos',
        },
        {
          visible: this.authS.onValidateRoles([
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Mtto Preventivo',
          routerLink: '/mantenimiento/calendario-anual',
          name: 'Calendario-Mantenimiento preventivo',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Fiestas Judías',
          routerLink: '/calendario/fiestas-judias',
          name: 'Calendario-Fiestaws judias',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Fiestas Catolicas',
          routerLink: '/calendario/fiestas-cristianas',
          name: 'Calendario-Fiestaws catolicas',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'Contador',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Cumpleaños',
          routerLink: '/calendario/cumpleanos',
          name: 'Calendario-Cumpleaños',
        },
      ],
    },

    {
      visible: this.authS.onValidateRoles([
        'Asistente',
        'GerenteMantenimiento',
        'JefeMantenimiento',
        'Administrador',
        'SuperUsuario',
        'SupervisionOperativa',
      ]),
      label: '5.13 Directorios',
      icon: 'fa-duotone fa-solid fa-address-book',
      items: [
        {
          visible: this.authS.onValidateRoles([
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Organigrama',
          routerLink: '/directory/organigrama-interno',
          name: 'Directorio-Organigrama interno',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Clientes',
          routerLink: '/settings/clientes',
          name: 'Directorio-Clientes',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Propiedades',
          routerLink: '/directory/propiedades',
          name: 'Directorio-Propiedades',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Condominos',
          routerLink: '/directory/condominos',
          name: 'Directorio-Condominos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Comité de vigilancia',
          routerLink: '/directory/comite-vigilancia',
          name: 'Directorio-Comité de vigilancia',
        },

        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Personal Interno',
          routerLink: '/directory/personal-interno',
          name: 'Directorio-Empleados internos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Catalogo deProveedores',
          routerLink: '/directory/proveedor',
          name: 'Directorio-Proveedores',
        },

        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Personal Externo',
          routerLink: '/directory/personal-externo',
          name: 'Directorio-Empleados externos',
        },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Mis Proveedores',
          routerLink: '/directory/mis-proveedores',
          name: 'Operaciones-Mis proveedores',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Supervisores de proveedores',
          routerLink: '/settings/supplier-supervisors',
          name: 'supplier-supervisors',
        },
        // {
        //   visible: this.authS.onValidateRoles(['SuperUsuario']),
        //   label: 'Personal General',
        //   routerLink: '/directory/empleados-general',
        //   name: 'Directorio-Todos los empleados',
        // },
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'GerenteMantenimiento',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
          ]),
          label: 'Tél. de Emergencias',
          routerLink: '/directory/telefonos-emergencia',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles([
        'Asistente',
        'GerenteMantenimiento',
        'JefeMantenimiento',
        'Administrador',
        'SuperUsuario',
        'SupervisionOperativa',
      ]),
      label: 'Reportes',
      icon: 'fa-duotone fa-solid fa-file-chart-column',
      items: [
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Historial de acceso',
          routerLink: '/report/access-history',
          name: 'access-history',
        },
        {
          visible: true,
          label: 'Minutas juntas con comite',
          routerLink: '/report/pending-minutes',
          name: 'access-history',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Mantenimientos preventivos',
          routerLink: '/',
          name: 'access-history',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Tickets de mantenimiento',
          routerLink: '/',
          name: 'access-history',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Presetnaciones de juntas',
          routerLink: '/',
          name: 'access-history',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Estados financieros',
          routerLink: '/',
          name: 'access-history',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Polizas',
          routerLink: '/',
          name: 'access-history',
        },
        {
          visible: this.authS.onValidateRoles(['SuperUsuario']),
          label: 'Proyectos',
          routerLink: '/',
          name: 'access-history',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles([
        'Asistente',
        'JefeMantenimiento',
        'Administrador',
        'SuperUsuario',
      ]),
      label: '6.2-Utilidades',
      icon: 'fa-duotone fa-solid fa-screwdriver-wrench',
      items: [
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'JefeMantenimiento',
            'Administrador',
            'SuperUsuario',
          ]),
          label: 'Calculadora IVA',
          routerLink: '/utilidades/calcular-iva',
          name: 'utilidades-Calculadora',
        },
      ],
    },
    {
      visible: this.authS.onValidateRoles([
        'Asistente',
        'Administrador',
        'SuperUsuario',
        'Reclutamiento',
      ]),
      label: '7.0 Reclutamiento',
      icon: 'fa-duotone fa-solid fa-arrows-down-to-people',
      items: [
        {
          visible: this.authS.onValidateRoles([
            'Asistente',
            'Administrador',
            'SuperUsuario',
            'SupervisionOperativa',
            'Reclutamiento',
          ]),
          label: 'Plantilla',
          routerLink: '/reclutamiento/plantilla-interna',
          name: 'Reclutamiento-Plantilla',
        },
        {
          visible: this.authS.onValidateRoles([
            'SuperUsuario',
            'Administrador',
            'Asistente',
          ]),
          label: 'Solicitudes',
          routerLink: '/reclutamiento/solicitudes_cliente',
          name: 'Reclutamiento-Solicitudes por cliente',
        },
        {
          visible: this.authS.onValidateRoles([
            'SuperUsuario',
            'Reclutamiento',
          ]),
          label: 'Solicitudes Recl',
          routerLink: '/reclutamiento/solicitudes/vacantes',
          name: 'Reclutamiento-Solicitudes a reclutamiento',
        },
        {
          visible: this.authS.onValidateRoles([
            'SuperUsuario',
            'Reclutamiento',
          ]),
          label: 'Profesiones',
          routerLink: '/catalog/jobs',
          name: 'Reclutamiento-Profesiones',
        },
      ],
    },
  ];
}
