import { AuthService } from 'src/app/core/services/auth.service';

export const settingMenu = (authS: AuthService) => [
  {
    group: 'Permisos',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Administración de Usuarios',
    icon: 'fa-duotone fa-solid fa-user-tie',
    routerLink: '/settings/application-user',
  },
  {
    group: 'Permisos',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Administración Roles Modulos',
    icon: 'fa-duotone fa-solid fa-key',
    routerLink: '/settings/module-app-rol',
  },
  {
    group: 'Permisos',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Clientes (Condominios)',
    icon: 'fa-duotone fa-solid fa-building',
    routerLink: '/settings/clientes',
  },
  {
    group: 'Permisos',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Modulos a Clientes',
    routerLink: '/settings/customer-modul',
    icon: 'fa-duotone fa-solid fa-layer-group',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Catalogo de Modulos',
    routerLink: '/settings/module-app',
    icon: 'fa-duotone fa-solid fa-layer-group',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Roles',
    routerLink: '/settings/roles',
    icon: 'fa fa-users',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Bancos',
    routerLink: '/settings/banks',
    icon: 'fa fa-university',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Forma de pago',
    routerLink: '/settings/forma-pago',
    icon: 'fa fa-credit-card',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Metodo de pago',
    routerLink: '/settings/metodo-pago',
    icon: 'fa fa-wallet',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Uso de cfdi',
    routerLink: '/settings/uso-cfdi',
    icon: 'fa fa-file-invoice',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Catalogo de cuentas contables',
    routerLink: '/contabilidad/catalogo-cuentas',
    icon: 'fa fa-book',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Departamentos de trabajo',
    routerLink: '/settings/company-departaments',
    icon: 'fa fa-building',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Profesiones',
    routerLink: '/settings/jobs',
    icon: 'fa fa-briefcase',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Categorias ticket',
    routerLink: '/settings/ticket-group-category',
    icon: 'fa fa-tags',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Categoria Medidor',
    routerLink: '/settings/meter-category',
    icon: 'fa fa-tachometer-alt',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Categoria productos',
    routerLink: '/settings/product-category',
    icon: 'fa fa-cogs',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Clasificacion equipos',
    routerLink: '/settings/machinery-classification',
    icon: 'fa fa-cogs',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Unidades de medida',
    routerLink: '/settings/units-of-measurement',
    icon: 'fa fa-ruler',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Entrega Recepción',
    routerLink: '/settings/entrega-recepcion-cliente',
    icon: 'fa fa-handshake',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Calendario maestro mtto',
    routerLink: '/calendario/calendario-maestro-equipo',
    icon: 'fa fa-calendar-alt',
  },

  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Catalogo de amenidades',
    routerLink: '/settings/catalog-asset',
    icon: 'fa fa-cogs',
  },
  {
    group: 'Catalogos de sistema',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Catalogo de inspecciones',
    routerLink: '/settings/inspection-reviews-catalog',
    icon: 'fa fa-search',
  },
  {
    group: 'configuracion de correos',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Emails corporativos',
    routerLink: '/settings/customer-data-company',
    icon: 'fa fa-envelope',
  },
  {
    group: 'configuracion de correos',
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Datos de email',
    routerLink: '/settings/datos-email',
    icon: 'fa fa-envelope-open',
  },
  {
    visible: authS.onValidateRoles(['SuperUsuario']),
    label: 'Depuración',
    routerLink: '/settings/depuration',
    icon: 'fa fa-bug',
  },
];
