export enum ERelationEmployee {
  'Abuelos',
  'Bisabuelos',
  'Bisnietos',
  'Hermanos',
  'Hijos',
  'Nietos',
  'Padres',
  'Primos',
  'Primos Sobrinos',
  'Primos Tíos',
  'Sobrinos',
  'Sobrinos Bisnietos',
  'Sobrinos Nietos',
  'Tatar Abuelos',
  'Tatara Nietos',
  'Tíos',
  'Tíos Abuelos',
  'Tíos Bisabuelos',
  'Trastatar Abuelos',
  'Trastataranietos',
  'Conyuge',
}
