// export { applicationUserMenu } from '../../routing/application-user.menu';
export { almacenMenu } from '../../routing/aprobate/almacen.menu';
export { comprasMenu } from '../../routing/aprobate/compras.menu';
export { inspectionMenu } from '../../routing/aprobate/inspection.menu';
export { juntasDeComiteMenu } from '../../routing/aprobate/juntas-comite.menu';
export { legalMenu } from '../../routing/aprobate/legal-menu';
export { ticketsMenu } from '../../routing/aprobate/tickets.menu';
export { calendarMenu } from '../../routing/calendar.menu';
export { contabilidadMenu } from '../../routing/contabilidad.menu';
// export { dashboardMenu } from '../../routing/dashboard.menu';
export { directoryMenu } from '../../routing/directorios.menu';
export { libraryMenu } from '../../routing/documentos-menu';
export { entregaRecepcionMenu } from '../../routing/entrega-recepcion.menu';
export { inventariosMenu } from '../../routing/inventarios.menu';
// export { mailsEmpresaMenu } from '../../routing/mails-empresa';
export { miEdificioMenu } from '../../routing/mi-edificio.menu';
export { mttoBitacorasMenu } from '../../routing/mtto-bitacoras.menu';
// export { mttoPreventivoMenu } from '../../routing/mtto-preventivo.menu';
export { reclutamientoMenu } from '../../routing/reclutamiento.menu';
export { reportMenu } from '../../routing/report-menu-item';
export { settingMenu } from '../../routing/settings-menu';
export { sistemasMenu } from '../../routing/sistemas.menu';
export { supervisionMenu } from '../../routing/supervision.menu';
export { utilidadesMenu } from '../../routing/utilidades.menu';
